version: '3.9'
services:
  app:
    build: .
    container_name: monitoring-node-app
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    working_dir: /app
    command: yarn dev

  postgres:
    image: "postgres:17.4"
    container_name: "postgres"
    volumes:
      - pgdata:/var/lib/postgresql/data/
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=metrics-node-app
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin-ira-pw

volumes:
  pgdata:
    name: pgdata
